### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by samsinsane** [Black-Sphere-Studios/tinyoal#1]
When opening an unsupported WAV file a divide by zero error occurs, I'm pretty sure it occurs in the cAudioResourceWAV constructor line 48.

**Comment by ErikMcClure** [comment]
I'm going to guess the correct fix here is to either move the !_format check earlier in the function, or insert a few extra "if zero don't blow up" checks, but before I blindly go changing code, do you have an example of an unsupported wave file I could repro this bug with?

**Comment by samsinsane** [comment]
http://www.nch.com.au/acm/11kadpcm.wav I was able to replicate the issue with this file, which is listed on the Wikipedia page for WAV, https://en.wikipedia.org/wiki/WAV#WAV_file_audio_coding_formats_compared hope that helps narrow it down :)

**Comment by ErikMcClure** [comment]
This bug turns out to be a bit more subtle than I anticipated. While the format itself is technically not supported, it actually is a valid format. The real bug here is that **all** formats with less than 8 bits per sample will divide by zero. This was fixed by forcing the byte calculation to work in terms of bits, and only convert down to bytes afterwards. I wasn't able to do this elsewhere due to precision concerns, but TinyOAL doesn't support any 4 bit formats anyway.

In addition to this, I've added a few checks to prevent any divide by zeros that might occur from null format data.
